version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: manjiltamang/store-app:v1
    restart: always
    ports:
      - "3005:3005"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: manjiltamang/store-api:v1
    restart: always
    ports:
      - "1337:1337"
