version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: yatrimotorcycles/yatristore-app:v1
    restart: always
    ports:
      - '3005:3005'

  strapi-api:
    build:
      context: ./strapi-api
      dockerfile: Dockerfile
    image: yatrimotorcycles/yatristore-strapi-api:v1
    restart: always
    ports:
      - '3006:3006'
