name: Release

on:
  release:
    branches:
      - 'master'
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

     - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.PRODUCTION_KEY }}
        with:
          source: '.'
          target: '~/apps/store.yatrimotorcycles.com'

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/apps/store.yatrimotorcycles.com
            docker-compose -f docker-compose.prod.yml up --build -d